In [1]:
!pip install -U vnstock

Requirement already satisfied: vnstock in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (3.4.2)
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (4.12.2)
Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (2.1.1)
Requirement already satisfied: seaborn in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (0.12.2)
Requirement already satisfied: openpyxl in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (3.1.2)
Requirement already satisfied: pydantic in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (2.12.5)
Requirement already satisfied: psutil in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (5.9.5)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (23.1)
Requirement already satisfied: importlib-metadata>=1.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (8.2.0)
Requirement already satisfied: tenacity in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (9.0.0)
Requirement already satisfied: vnai>=2.3.9 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (2.3.9)
Requirement already satisfied: vnstock_ezchart>=0.0.3 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock) (0.0.3)
Requirement already satisfied: zipp>=0.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from importlib-metadata>=1.0->vnstock) (3.19.2)
Requirement already satisfied: cffi>=1.17.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnai>=2.3.9->vnstock) (2.0.0)
Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from cffi>=1.17.1->vnai>=2.3.9->vnstock) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests->vnstock) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests->vnstock) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests->vnstock) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests->vnstock) (2024.7.4)
Requirement already satisfied: squarify in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock_ezchart>=0.0.3->vnstock) (0.4.4)
Requirement already satisfied: wordcloud in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from vnstock_ezchart>=0.0.3->vnstock) (1.9.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4->vnstock) (2.4.1)
Requirement already satisfied: et-xmlfile in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from openpyxl->vnstock) (1.1.0)
Requirement already satisfied: numpy>=1.23.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas->vnstock) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas->vnstock) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas->vnstock) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas->vnstock) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas->vnstock) (1.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pydantic->vnstock) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pydantic->vnstock) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pydantic->vnstock) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pydantic->vnstock) (0.4.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from seaborn->vnstock) (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn->vnstock) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn->vnstock) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn->vnstock) (4.53.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn->vnstock) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn->vnstock) (10.3.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn->vnstock) (3.0.9)

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
from vnstock import Finance
finance = Finance(symbol='HPG', source='VCI')

In [8]:
finance.balance_sheet(period='quarter', lang='vi', dropna=True).head(10)

,CP,Năm,Kỳ,TÀI SẢN NGẮN HẠN (đồng),Tiền và tương đương tiền (đồng),Giá trị thuần đầu tư ngắn hạn (đồng),Các khoản phải thu ngắn hạn (đồng),Hàng tồn kho ròng,Tài sản lưu động khác,TÀI SẢN DÀI HẠN (đồng),...,Cổ phiếu phổ thông (đồng),Vốn góp của chủ sở hữu (đồng),Vay và nợ thuê tài chính dài hạn (đồng),Người mua trả tiền trước ngắn hạn (đồng),Vay và nợ thuê tài chính ngắn hạn (đồng),Lợi thế thương mại (đồng),Trả trước dài hạn (đồng),Tài sản dài hạn khác (đồng),Phải thu dài hạn khác (đồng),Phải thu dài hạn (đồng)
0,HPG,2025,4,103682043127964,8300890304205,19484412761405,15064703713293,52828227344442,8003809004619,154239538285186,...,76754658550000,76754658550000,27479194057074,862026330691,64694957245143,51513185419,6003368983150,0,248919079879,290327516308
1,HPG,2025,3,95425988115582,9092562739415,18903949054642,13727194725111,45623656431728,8078625164686,150745350172070,...,76754658550000,76754658550000,28356095137594,619205121131,68482383626253,52097751283,4390536576181,0,825562606009,849788287676
2,HPG,2025,2,97613904938535,10688024277258,17584027436423,12334925649801,48853408114115,8153519460938,144610625980515,...,63962502000000,63962502000000,27312288660990,306667783670,66692028477152,57563156071,4338725174159,0,827053815447,900453913211
3,HPG,2025,1,88914195573724,7459035818129,16212510112252,10856053423195,46603844415849,7782751804299,139947392214583,...,63962502000000,63962502000000,27256965869238,570631436241,61784512821075,60588141397,4261916994097,0,848015622228,920743791614
4,HPG,2024,4,86674276272995,6887646139852,18974716730905,7647800286988,46091222189472,7072890925778,137815431280986,...,63962502000000,63962502000000,27080443256096,739178306553,55882686213459,63613126723,4269141694868,0,840594835822,923400123614
5,HPG,2024,3,80841803394106,8500998079280,16386803148945,9140948029240,40197821463879,6615232672762,130544540534012,...,63962502000000,63962502000000,24517626484538,440576623880,54180722680952,66834062714,4347213561931,0,841682562478,1031145036427
6,HPG,2024,2,84466831221789,13032037853283,15314673148945,10392801855660,40163540620593,5563777743308,122142248509406,...,63962502000000,63962502000000,19674955314582,482276831033,53315313650059,69859048040,4612526104983,0,850381710697,1119456422036
7,HPG,2024,1,94032457790196,12428888036237,22271418573603,12105116296231,42714279935957,4512754948168,107907767738311,...,58147857000000,58147857000000,16080142067527,340776685682,61438295764670,72884033366,4558305203235,0,777913997306,1313739979740
8,HPG,2023,4,82716439173043,12267401160884,22161903502481,10702136439996,34504487406261,3080510663421,105066147390758,...,58147857000000,58147857000000,10399119292481,741733890580,54981883180636,75909018692,4215007972679,0,781079548004,1880922130348
9,HPG,2023,3,78482566275784,9696669423876,19957222511116,12506103872593,33524022785325,2798547682874,95024445408788,...,58147857000000,58147857000000,8744590378258,440272925867,49237590969260,78934004018,3940414512830,0,797360888746,893054450460

In [4]:
finance.income_statement(period='quarter', lang='vi', dropna=True).head()

,CP,Năm,Kỳ,Doanh thu (đồng),Tăng trưởng doanh thu (%),Lợi nhuận sau thuế của Cổ đông công ty mẹ (đồng),Tăng trưởng lợi nhuận (%),Thu nhập lãi và các khoản tương tự,Chi phí lãi và các khoản tương tự,Thu nhập lãi thuần,...,Chi phí quản lý DN,LN từ HĐKD trước CF dự phòng,Chi phí dự phòng rủi ro tín dụng,LN trước thuế,Thuế TNDN,Chi phí thuế TNDN hiện hành,Chi phí thuế TNDN hoãn lại,Lợi nhuận thuần,Cổ đông của Công ty mẹ,Lãi cơ bản trên cổ phiếu
0,ACB,2025,4,16080424000000,0.189523,2784685000000,-0.387357,16080424000000,-8987152000000,7093272000000,...,-2782374000000,5423672000000,-1956645000000,3467027000000,-682342000000,-663269000000,-19073000000,2784685000000,2784685000000,0
1,ACB,2025,3,15049404000000,0.164628,4280589000000,0.105982,15049404000000,-8279694000000,6769710000000,...,-2713933000000,5670732000000,-288936000000,5381796000000,-1101207000000,-1081502000000,-19705000000,4280589000000,4280589000000,0
2,ACB,2025,2,14298695000000,0.146214,4881159000000,0.092326,14298695000000,-7614847000000,6683848000000,...,-2736160000000,6556384000000,-463039000000,6093345000000,-1212186000000,-1210700000000,-1486000000,4881159000000,4881159000000,0
3,ACB,2025,1,13327306000000,0.111758,3678266000000,-0.058164,13327306000000,-6968441000000,6358865000000,...,-2691892000000,5222736000000,-626128000000,4596608000000,-918342000000,-958551000000,40209000000,3678266000000,3678266000000,0
4,ACB,2024,4,13518376000000,0.080173,4545364000000,0.134560,13518376000000,-6438085000000,7080291000000,...,-2739350000000,5818946000000,-147675000000,5671271000000,-1125907000000,-1086127000000,-39780000000,4545364000000,4545364000000,1017

In [5]:
finance.income_statement(period='quarter', lang='vi', dropna=True).head()

,CP,Năm,Kỳ,Doanh thu (đồng),Tăng trưởng doanh thu (%),Lợi nhuận sau thuế của Cổ đông công ty mẹ (đồng),Tăng trưởng lợi nhuận (%),Thu nhập lãi và các khoản tương tự,Chi phí lãi và các khoản tương tự,Thu nhập lãi thuần,...,Chi phí quản lý DN,LN từ HĐKD trước CF dự phòng,Chi phí dự phòng rủi ro tín dụng,LN trước thuế,Thuế TNDN,Chi phí thuế TNDN hiện hành,Chi phí thuế TNDN hoãn lại,Lợi nhuận thuần,Cổ đông của Công ty mẹ,Lãi cơ bản trên cổ phiếu
0,ACB,2025,4,16080424000000,0.189523,2784685000000,-0.387357,16080424000000,-8987152000000,7093272000000,...,-2782374000000,5423672000000,-1956645000000,3467027000000,-682342000000,-663269000000,-19073000000,2784685000000,2784685000000,0
1,ACB,2025,3,15049404000000,0.164628,4280589000000,0.105982,15049404000000,-8279694000000,6769710000000,...,-2713933000000,5670732000000,-288936000000,5381796000000,-1101207000000,-1081502000000,-19705000000,4280589000000,4280589000000,0
2,ACB,2025,2,14298695000000,0.146214,4881159000000,0.092326,14298695000000,-7614847000000,6683848000000,...,-2736160000000,6556384000000,-463039000000,6093345000000,-1212186000000,-1210700000000,-1486000000,4881159000000,4881159000000,0
3,ACB,2025,1,13327306000000,0.111758,3678266000000,-0.058164,13327306000000,-6968441000000,6358865000000,...,-2691892000000,5222736000000,-626128000000,4596608000000,-918342000000,-958551000000,40209000000,3678266000000,3678266000000,0
4,ACB,2024,4,13518376000000,0.080173,4545364000000,0.134560,13518376000000,-6438085000000,7080291000000,...,-2739350000000,5818946000000,-147675000000,5671271000000,-1125907000000,-1086127000000,-39780000000,4545364000000,4545364000000,1017